/**
 * 発注生産システムの仕入先マスタのModel.
 */
export class JunpcSirmst {
  /** ID */
  id: number;
  /** 仕入れ先コード */
  sire: string;
  // sirkbn: string;
  // sname: string;
  /** 仕入れ先名 */
  name: string;
  // yubin: string;
  // add1: string;
  // add2: string;
  // add3: string;
  // tel1: string;
  // fax1: string;
  // bank: string;
  // siten: string;
  // kozsyu: string;
  // kozno: string;
  // meigij: string;
  // meigik: string;
  // city: string;
  // dummy1: string;
  // brand1: string;
  // himok1: string;
  // brand2: string;
  // himok2: string;
  // brand3: string;
  // himok3: string;
  // brand4: string;
  // himok4: string;
  // brand5: string;
  // himok5: string;
  // brand6: string;
  // himok6: string;
  // brand7: string;
  // himok7: string;
  // brand8: string;
  // himok8: string;
  // brand9: string;
  // himok9: string;
  // brand10: string;
  // himok10: string;
  // brand11: string;
  // himok11: string;
  // brand12: string;
  // himok12: string;
  // brand13: string;
  // himok13: string;
  // brand14: string;
  // himok14: string;
  // brand15: string;
  // himok15: string;
  // brand16: string;
  // himok16: string;
  // brand17: string;
  // himok17: string;
  // brand18: string;
  // himok18: string;
  // brand19: string;
  // himok19: string;
  // brand20: string;
  // himok20: string;
  // brand21: string;
  // himok21: string;
  // brand22: string;
  // himok22: string;
  // brand23: string;
  // himok23: string;
  // brand24: string;
  // himok24: string;
  // brand25: string;
  // himok25: string;
  // brand26: string;
  // himok26: string;
  // brand27: string;
  // himok27: string;
  // brand28: string;
  // himok28: string;
  // brand29: string;
  // himok29: string;
  // brand30: string;
  // himok30: string;
  // ftesury: string;
  // bubkbn: string;
  // sofkbn: string;
  // hkiji: string;
  // hseihin: string;
  // hnefuda: string;
  // hfuzoku: string;
  // sofhou: string;
  // dummy2: string;
  // lokkbn: string;
  /** 送信フラグ */
  souflg: string;
  // mntflg: string;
  // tanto: string;
  // crtymd: string;
  // updymd: string;
  // pgid: string;
  // souflga: string;
  // souymda: string;
  /** 有害区分 */
  yugaikbn: string;
  // yugaiymd: string;
}
